junit_tests(
  name = "test",
  dependencies=[
    'scalding-serialization/src/main',
    '3rdparty/jvm:junit',
    '3rdparty/jvm:scalacheck',
    '3rdparty/jvm:scalatest',
  ],
  sources = rglobs("*.scala", "*.java"),
)
