java_library(
  name = "maple",
  srcs = glob(["**/*.java"]),
  deps = [
    "@cascading-core//jar",
    "@cascading-hadoop//jar",
    "@cascading-local//jar",
    "@commons-codec//jar",
    "@commons-logging//jar",
    "@hadoop-client//jar",
    "@hadoop-common//jar",
    "@hbase//jar",
    "@slf4j-api//jar",
  ],
  visibility = ["//visibility:public"]
  )
