java_library(
  name = "main",
  sources = rglobs("*.java"),
  dependencies = [
    "3rdparty/jvm:cascading-core",
    "3rdparty/jvm:cascading-hadoop",
    "3rdparty/jvm:cascading-local",
    "3rdparty/jvm:commons-codec",
    "3rdparty/jvm:commons-logging",
    "3rdparty/jvm:hadoop-client",
    "3rdparty/jvm:hadoop-common",
    "3rdparty/jvm:hbase",
    "3rdparty/jvm:slf4j-api",
  ],
)
