// following were autogenerated by ./codegen/multi_join_generator.rb at Wed Nov 19 00:00:14 -0800 2014 do not edit
package com.twitter.scalding

import com.twitter.scalding.typed.CoGroupable

trait GeneratedCoGroupableMultiJoins[KEY, +VALUE] { self: CoGroupable[KEY, VALUE] =>
  import com.twitter.scalding.FlattenGroup._

  def leftJoin[A, B](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B]): CoGroupable[KEY, (VALUE, Option[A], Option[B])] = {
    leftJoin(a)
      .leftJoin(b)
      .flattenGrouped
  }

  def leftJoin[A, B, C](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I, J](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .leftJoin(j)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I, J, K](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .leftJoin(j)
      .leftJoin(k)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I, J, K, L](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .leftJoin(j)
      .leftJoin(k)
      .leftJoin(l)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I, J, K, L, M](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .leftJoin(j)
      .leftJoin(k)
      .leftJoin(l)
      .leftJoin(m)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .leftJoin(j)
      .leftJoin(k)
      .leftJoin(l)
      .leftJoin(m)
      .leftJoin(n)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .leftJoin(j)
      .leftJoin(k)
      .leftJoin(l)
      .leftJoin(m)
      .leftJoin(n)
      .leftJoin(o)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O], p: CoGroupable[KEY, P]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O], Option[P])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .leftJoin(j)
      .leftJoin(k)
      .leftJoin(l)
      .leftJoin(m)
      .leftJoin(n)
      .leftJoin(o)
      .leftJoin(p)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O], p: CoGroupable[KEY, P], q: CoGroupable[KEY, Q]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O], Option[P], Option[Q])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .leftJoin(j)
      .leftJoin(k)
      .leftJoin(l)
      .leftJoin(m)
      .leftJoin(n)
      .leftJoin(o)
      .leftJoin(p)
      .leftJoin(q)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O], p: CoGroupable[KEY, P], q: CoGroupable[KEY, Q], r: CoGroupable[KEY, R]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O], Option[P], Option[Q], Option[R])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .leftJoin(j)
      .leftJoin(k)
      .leftJoin(l)
      .leftJoin(m)
      .leftJoin(n)
      .leftJoin(o)
      .leftJoin(p)
      .leftJoin(q)
      .leftJoin(r)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O], p: CoGroupable[KEY, P], q: CoGroupable[KEY, Q], r: CoGroupable[KEY, R], s: CoGroupable[KEY, S]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O], Option[P], Option[Q], Option[R], Option[S])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .leftJoin(j)
      .leftJoin(k)
      .leftJoin(l)
      .leftJoin(m)
      .leftJoin(n)
      .leftJoin(o)
      .leftJoin(p)
      .leftJoin(q)
      .leftJoin(r)
      .leftJoin(s)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O], p: CoGroupable[KEY, P], q: CoGroupable[KEY, Q], r: CoGroupable[KEY, R], s: CoGroupable[KEY, S], t: CoGroupable[KEY, T]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O], Option[P], Option[Q], Option[R], Option[S], Option[T])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .leftJoin(j)
      .leftJoin(k)
      .leftJoin(l)
      .leftJoin(m)
      .leftJoin(n)
      .leftJoin(o)
      .leftJoin(p)
      .leftJoin(q)
      .leftJoin(r)
      .leftJoin(s)
      .leftJoin(t)
      .flattenGrouped
  }

  def leftJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O], p: CoGroupable[KEY, P], q: CoGroupable[KEY, Q], r: CoGroupable[KEY, R], s: CoGroupable[KEY, S], t: CoGroupable[KEY, T], u: CoGroupable[KEY, U]): CoGroupable[KEY, (VALUE, Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O], Option[P], Option[Q], Option[R], Option[S], Option[T], Option[U])] = {
    leftJoin(a)
      .leftJoin(b)
      .leftJoin(c)
      .leftJoin(d)
      .leftJoin(e)
      .leftJoin(f)
      .leftJoin(g)
      .leftJoin(h)
      .leftJoin(i)
      .leftJoin(j)
      .leftJoin(k)
      .leftJoin(l)
      .leftJoin(m)
      .leftJoin(n)
      .leftJoin(o)
      .leftJoin(p)
      .leftJoin(q)
      .leftJoin(r)
      .leftJoin(s)
      .leftJoin(t)
      .leftJoin(u)
      .flattenGrouped
  }

  def outerJoin[A, B](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B])] = {
    outerJoin(a)
      .outerJoin(b)
      .flattenGrouped
  }

  def outerJoin[A, B, C](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I, J](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .outerJoin(j)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I, J, K](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .outerJoin(j)
      .outerJoin(k)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I, J, K, L](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .outerJoin(j)
      .outerJoin(k)
      .outerJoin(l)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I, J, K, L, M](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .outerJoin(j)
      .outerJoin(k)
      .outerJoin(l)
      .outerJoin(m)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .outerJoin(j)
      .outerJoin(k)
      .outerJoin(l)
      .outerJoin(m)
      .outerJoin(n)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .outerJoin(j)
      .outerJoin(k)
      .outerJoin(l)
      .outerJoin(m)
      .outerJoin(n)
      .outerJoin(o)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O], p: CoGroupable[KEY, P]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O], Option[P])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .outerJoin(j)
      .outerJoin(k)
      .outerJoin(l)
      .outerJoin(m)
      .outerJoin(n)
      .outerJoin(o)
      .outerJoin(p)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O], p: CoGroupable[KEY, P], q: CoGroupable[KEY, Q]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O], Option[P], Option[Q])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .outerJoin(j)
      .outerJoin(k)
      .outerJoin(l)
      .outerJoin(m)
      .outerJoin(n)
      .outerJoin(o)
      .outerJoin(p)
      .outerJoin(q)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O], p: CoGroupable[KEY, P], q: CoGroupable[KEY, Q], r: CoGroupable[KEY, R]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O], Option[P], Option[Q], Option[R])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .outerJoin(j)
      .outerJoin(k)
      .outerJoin(l)
      .outerJoin(m)
      .outerJoin(n)
      .outerJoin(o)
      .outerJoin(p)
      .outerJoin(q)
      .outerJoin(r)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O], p: CoGroupable[KEY, P], q: CoGroupable[KEY, Q], r: CoGroupable[KEY, R], s: CoGroupable[KEY, S]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O], Option[P], Option[Q], Option[R], Option[S])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .outerJoin(j)
      .outerJoin(k)
      .outerJoin(l)
      .outerJoin(m)
      .outerJoin(n)
      .outerJoin(o)
      .outerJoin(p)
      .outerJoin(q)
      .outerJoin(r)
      .outerJoin(s)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O], p: CoGroupable[KEY, P], q: CoGroupable[KEY, Q], r: CoGroupable[KEY, R], s: CoGroupable[KEY, S], t: CoGroupable[KEY, T]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O], Option[P], Option[Q], Option[R], Option[S], Option[T])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .outerJoin(j)
      .outerJoin(k)
      .outerJoin(l)
      .outerJoin(m)
      .outerJoin(n)
      .outerJoin(o)
      .outerJoin(p)
      .outerJoin(q)
      .outerJoin(r)
      .outerJoin(s)
      .outerJoin(t)
      .flattenGrouped
  }

  def outerJoin[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U](a: CoGroupable[KEY, A], b: CoGroupable[KEY, B], c: CoGroupable[KEY, C], d: CoGroupable[KEY, D], e: CoGroupable[KEY, E], f: CoGroupable[KEY, F], g: CoGroupable[KEY, G], h: CoGroupable[KEY, H], i: CoGroupable[KEY, I], j: CoGroupable[KEY, J], k: CoGroupable[KEY, K], l: CoGroupable[KEY, L], m: CoGroupable[KEY, M], n: CoGroupable[KEY, N], o: CoGroupable[KEY, O], p: CoGroupable[KEY, P], q: CoGroupable[KEY, Q], r: CoGroupable[KEY, R], s: CoGroupable[KEY, S], t: CoGroupable[KEY, T], u: CoGroupable[KEY, U]): CoGroupable[KEY, (Option[VALUE], Option[A], Option[B], Option[C], Option[D], Option[E], Option[F], Option[G], Option[H], Option[I], Option[J], Option[K], Option[L], Option[M], Option[N], Option[O], Option[P], Option[Q], Option[R], Option[S], Option[T], Option[U])] = {
    outerJoin(a)
      .outerJoin(b)
      .outerJoin(c)
      .outerJoin(d)
      .outerJoin(e)
      .outerJoin(f)
      .outerJoin(g)
      .outerJoin(h)
      .outerJoin(i)
      .outerJoin(j)
      .outerJoin(k)
      .outerJoin(l)
      .outerJoin(m)
      .outerJoin(n)
      .outerJoin(o)
      .outerJoin(p)
      .outerJoin(q)
      .outerJoin(r)
      .outerJoin(s)
      .outerJoin(t)
      .outerJoin(u)
      .flattenGrouped
  }

}
// end of autogenerated
