// following were autogenerated by ./codegen/typed_source_generator.rb at 2013-09-19 15:33:02 -0700 do not edit
package com.twitter.scalding

trait TypedSource1[A] extends TypedSource[Tuple1[A]] {
  def converter[Z >: Tuple1[A]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple1[A]])
}

trait TypedSource2[A,B] extends TypedSource[Tuple2[A,B]] {
  def converter[Z >: Tuple2[A,B]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple2[A,B]])
}

trait TypedSource3[A,B,C] extends TypedSource[Tuple3[A,B,C]] {
  def converter[Z >: Tuple3[A,B,C]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple3[A,B,C]])
}

trait TypedSource4[A,B,C,D] extends TypedSource[Tuple4[A,B,C,D]] {
  def converter[Z >: Tuple4[A,B,C,D]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple4[A,B,C,D]])
}

trait TypedSource5[A,B,C,D,E] extends TypedSource[Tuple5[A,B,C,D,E]] {
  def converter[Z >: Tuple5[A,B,C,D,E]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple5[A,B,C,D,E]])
}

trait TypedSource6[A,B,C,D,E,F] extends TypedSource[Tuple6[A,B,C,D,E,F]] {
  def converter[Z >: Tuple6[A,B,C,D,E,F]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple6[A,B,C,D,E,F]])
}

trait TypedSource7[A,B,C,D,E,F,G] extends TypedSource[Tuple7[A,B,C,D,E,F,G]] {
  def converter[Z >: Tuple7[A,B,C,D,E,F,G]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple7[A,B,C,D,E,F,G]])
}

trait TypedSource8[A,B,C,D,E,F,G,H] extends TypedSource[Tuple8[A,B,C,D,E,F,G,H]] {
  def converter[Z >: Tuple8[A,B,C,D,E,F,G,H]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple8[A,B,C,D,E,F,G,H]])
}

trait TypedSource9[A,B,C,D,E,F,G,H,I] extends TypedSource[Tuple9[A,B,C,D,E,F,G,H,I]] {
  def converter[Z >: Tuple9[A,B,C,D,E,F,G,H,I]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple9[A,B,C,D,E,F,G,H,I]])
}

trait TypedSource10[A,B,C,D,E,F,G,H,I,J] extends TypedSource[Tuple10[A,B,C,D,E,F,G,H,I,J]] {
  def converter[Z >: Tuple10[A,B,C,D,E,F,G,H,I,J]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple10[A,B,C,D,E,F,G,H,I,J]])
}

trait TypedSource11[A,B,C,D,E,F,G,H,I,J,K] extends TypedSource[Tuple11[A,B,C,D,E,F,G,H,I,J,K]] {
  def converter[Z >: Tuple11[A,B,C,D,E,F,G,H,I,J,K]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple11[A,B,C,D,E,F,G,H,I,J,K]])
}

trait TypedSource12[A,B,C,D,E,F,G,H,I,J,K,L] extends TypedSource[Tuple12[A,B,C,D,E,F,G,H,I,J,K,L]] {
  def converter[Z >: Tuple12[A,B,C,D,E,F,G,H,I,J,K,L]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple12[A,B,C,D,E,F,G,H,I,J,K,L]])
}

trait TypedSource13[A,B,C,D,E,F,G,H,I,J,K,L,M] extends TypedSource[Tuple13[A,B,C,D,E,F,G,H,I,J,K,L,M]] {
  def converter[Z >: Tuple13[A,B,C,D,E,F,G,H,I,J,K,L,M]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple13[A,B,C,D,E,F,G,H,I,J,K,L,M]])
}

trait TypedSource14[A,B,C,D,E,F,G,H,I,J,K,L,M,N] extends TypedSource[Tuple14[A,B,C,D,E,F,G,H,I,J,K,L,M,N]] {
  def converter[Z >: Tuple14[A,B,C,D,E,F,G,H,I,J,K,L,M,N]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple14[A,B,C,D,E,F,G,H,I,J,K,L,M,N]])
}

trait TypedSource15[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O] extends TypedSource[Tuple15[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O]] {
  def converter[Z >: Tuple15[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple15[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O]])
}

trait TypedSource16[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P] extends TypedSource[Tuple16[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P]] {
  def converter[Z >: Tuple16[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple16[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P]])
}

trait TypedSource17[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q] extends TypedSource[Tuple17[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q]] {
  def converter[Z >: Tuple17[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple17[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q]])
}

trait TypedSource18[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R] extends TypedSource[Tuple18[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R]] {
  def converter[Z >: Tuple18[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple18[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R]])
}

trait TypedSource19[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S] extends TypedSource[Tuple19[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S]] {
  def converter[Z >: Tuple19[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple19[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S]])
}

trait TypedSource20[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T] extends TypedSource[Tuple20[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T]] {
  def converter[Z >: Tuple20[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple20[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T]])
}

trait TypedSource21[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U] extends TypedSource[Tuple21[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U]] {
  def converter[Z >: Tuple21[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U]] = TupleConverter.asSuperConverter(TupleConverter.of[Tuple21[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U]])
}

// end of autogenerated
